version: "3"
services:
  db:
    image: postgres:latest
    container_name: ecommerce
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce_ums

    volumes:
      - /Users/abimana/2025/january/GOLANG/CAMPUS/e-commerce/ecommerce-ums/db:/var/lib/postgresql/data

